
zuul:
  routes:
    api-a:
      path: /user/**
      serviceId: pp-cloud-user
      
spring:
    application:
        name: service-zuul
server:
  port: 8001
eureka:
   instance:
     lease-renewal-interval-in-seconds: 1      # 心跳时间，即服务续约间隔时间（缺省为30s）
     lease-expiration-duration-in-seconds: 2  # 发呆时间，即服务续约到期时间（缺省为90s）
     hostname: localhost
     instance-id: ${spring.application.name}:${server.port}
   client:    
     service-url:
       defaultZone: http://s1:8801/eureka/,http://s2:8802/eureka/     
     healthcheck:
       enabled:true
   server:
     enable-self-preservation:false#关闭保护机制（缺省为打开）
     eviction-interval-timer-in-ms:1000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）

endpoints.shutdown.enabled: true    #开启优雅关闭方式
management.security.enabled: false  #关闭安全认证
